CREATE TABLE IF NOT EXISTS `history_readings` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `timestamp` INTEGER NOT NULL, `sensorSerial` TEXT NOT NULL, `value` REAL NOT NULL, `rawValue` REAL NOT NULL, `rate` REAL, `source` TEXT NOT NULL, `firstStoredAt` INTEGER NOT NULL)
CREATE UNIQUE INDEX IF NOT EXISTS `index_history_readings_timestamp_sensorSerial` ON `history_readings` (`timestamp`, `sensorSerial`)
CREATE INDEX IF NOT EXISTS `index_history_readings_sensorSerial` ON `history_readings` (`sensorSerial`)
CREATE INDEX IF NOT EXISTS `index_history_readings_sensorSerial_timestamp` ON `history_readings` (`sensorSerial`, `timestamp`)
CREATE TABLE IF NOT EXISTS `history_deleted_readings` (`timestamp` INTEGER NOT NULL, `sensorSerial` TEXT NOT NULL, `deletedAt` INTEGER NOT NULL, PRIMARY KEY(`timestamp`, `sensorSerial`))
CREATE INDEX IF NOT EXISTS `index_history_deleted_readings_sensorSerial` ON `history_deleted_readings` (`sensorSerial`)
CREATE TABLE IF NOT EXISTS `reading_uncertainty` (`sensorSerial` TEXT NOT NULL, `timestamp` INTEGER NOT NULL, `lowerMgdl` REAL NOT NULL, `upperMgdl` REAL NOT NULL, `intervalMass` REAL NOT NULL, `confidence` REAL, `artifactProbability` REAL, PRIMARY KEY(`sensorSerial`, `timestamp`))
CREATE INDEX IF NOT EXISTS `index_reading_uncertainty_timestamp` ON `reading_uncertainty` (`timestamp`)
CREATE TABLE IF NOT EXISTS `reading_display` (`timestamp` INTEGER NOT NULL, `sensorSerial` TEXT NOT NULL, `displayMgdl` REAL NOT NULL, `viewMode` INTEGER NOT NULL, `calibrationFingerprint` INTEGER NOT NULL, `recordedAt` INTEGER NOT NULL, PRIMARY KEY(`timestamp`))
CREATE INDEX IF NOT EXISTS `index_reading_display_sensorSerial` ON `reading_display` (`sensorSerial`)
CREATE TABLE IF NOT EXISTS `journal_entries` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `timestamp` INTEGER NOT NULL, `sensorSerial` TEXT, `entryType` TEXT NOT NULL, `title` TEXT NOT NULL, `note` TEXT, `amount` REAL, `glucoseValueMgDl` REAL, `durationMinutes` INTEGER, `intensity` TEXT, `insulinPresetId` INTEGER, `foodId` INTEGER, `proteinGrams` REAL, `fatGrams` REAL, `source` TEXT NOT NULL, `originSource` TEXT, `sourceRecordId` TEXT, `recoveryId` TEXT, `createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL, `nsUploadedAt` INTEGER, `nsRemoteId` TEXT, `insulinCurveJsonSnapshot` TEXT, `insulinCurveProfileId` TEXT, `insulinCurveModelVersion` INTEGER, `insulinCurveEvidence` TEXT, `insulinBodyWeightKg` REAL, `insulinCurveWasApproximated` INTEGER NOT NULL DEFAULT 0, `lvUploadedAt` INTEGER)
CREATE INDEX IF NOT EXISTS `index_journal_entries_timestamp` ON `journal_entries` (`timestamp`)
CREATE INDEX IF NOT EXISTS `index_journal_entries_entryType` ON `journal_entries` (`entryType`)
CREATE INDEX IF NOT EXISTS `index_journal_entries_insulinPresetId` ON `journal_entries` (`insulinPresetId`)
CREATE INDEX IF NOT EXISTS `index_journal_entries_foodId` ON `journal_entries` (`foodId`)
CREATE UNIQUE INDEX IF NOT EXISTS `index_journal_entries_sourceRecordId` ON `journal_entries` (`sourceRecordId`)
CREATE UNIQUE INDEX IF NOT EXISTS `index_journal_entries_recoveryId` ON `journal_entries` (`recoveryId`)
CREATE TABLE IF NOT EXISTS `journal_foods` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `displayName` TEXT NOT NULL, `carbsGrams` REAL NOT NULL, `proteinGrams` REAL, `fatGrams` REAL, `absorptionMinutes` INTEGER NOT NULL, `accentColor` INTEGER NOT NULL, `isBuiltIn` INTEGER NOT NULL, `isArchived` INTEGER NOT NULL, `sortOrder` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL)
CREATE INDEX IF NOT EXISTS `index_journal_foods_isArchived_sortOrder` ON `journal_foods` (`isArchived`, `sortOrder`)
CREATE INDEX IF NOT EXISTS `index_journal_foods_displayName` ON `journal_foods` (`displayName`)
CREATE TABLE IF NOT EXISTS `journal_insulin_presets` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `displayName` TEXT NOT NULL, `onsetMinutes` INTEGER NOT NULL, `durationMinutes` INTEGER NOT NULL, `accentColor` INTEGER NOT NULL, `curveJson` TEXT NOT NULL, `isBuiltIn` INTEGER NOT NULL, `isArchived` INTEGER NOT NULL, `countsTowardIob` INTEGER NOT NULL, `sortOrder` INTEGER NOT NULL, `useForCalculation` INTEGER NOT NULL DEFAULT 1, `curveProfileId` TEXT, `curveModelVersion` INTEGER NOT NULL DEFAULT 0, `curveEvidence` TEXT NOT NULL DEFAULT 'unverified')
CREATE INDEX IF NOT EXISTS `index_journal_insulin_presets_sortOrder` ON `journal_insulin_presets` (`sortOrder`)
CREATE TABLE IF NOT EXISTS `journal_pending_deletes` (`entryId` INTEGER NOT NULL, `nsRemoteId` TEXT NOT NULL, `deletedAt` INTEGER NOT NULL, `attempts` INTEGER NOT NULL, `lastAttemptAt` INTEGER NOT NULL, PRIMARY KEY(`entryId`))
CREATE TABLE IF NOT EXISTS `clone_journal_tombstones` (`entryId` INTEGER NOT NULL, `deletedAt` INTEGER NOT NULL, `recoveryId` TEXT, PRIMARY KEY(`entryId`))
CREATE TABLE IF NOT EXISTS `clone_journal_recovery_tombstones` (`stableBaseId` TEXT NOT NULL, `recoveryId` TEXT, `deletedAt` INTEGER NOT NULL, PRIMARY KEY(`stableBaseId`))
CREATE UNIQUE INDEX IF NOT EXISTS `index_clone_journal_recovery_tombstones_recoveryId` ON `clone_journal_recovery_tombstones` (`recoveryId`)
CREATE TABLE IF NOT EXISTS `clone_recovery_imports` (`jobId` TEXT NOT NULL, `sha256` TEXT NOT NULL, PRIMARY KEY(`jobId`))
CREATE TABLE IF NOT EXISTS room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT)
INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, '9a30610172d9abb562f6d85a2a59812d')
